services:
    laravel.test:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
            - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        networks:
            - laravel

    nuxt:
        build:
            context: .
            dockerfile: docker/nuxt/Dockerfile
        volumes:
            - ./client:/src
            - ./client/node_modules:/src/node_modules
        ports:
            - 3000:3000
            - 24678:24678
        networks:
            - laravel

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'db:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    laravel:
        driver: bridge
volumes:
    db:
        driver: local
    redis:
        driver: local
